

import { I18nKeys, Locale } from './types';

export const RESOURCES: Record<Locale, Record<I18nKeys, string>> = {
  'zh-CN': {
    'app.title': 'CineFlow 控制台',
    'nav.dashboard': '概览',
    'nav.storyboards': '分镜脚本',
    'nav.runs': '执行任务',
    'nav.results': '结果库',
    'nav.settings': '系统设置',
    'action.import': '导入脚本',
    'action.create_run': '创建任务',
    'action.save': '保存',
    'action.cancel': '取消',
    'action.delete': '删除',
    'action.retry': '重试',
    'action.view': '查看',
    'action.edit': '编辑',
    'action.filter': '筛选',
    'action.download': '下载视频',
    'action.download_meta': '下载元数据',
    'action.enable': '启用',
    'action.disable': '禁用',
    'action.details': '详情',
    'action.upload_ref': '上传参考图',
    'action.upload_click': '点击上传或拖拽文件',
    'action.apply_filter': '应用筛选',
    'action.clear_filter': '清除筛选',
    'action.connect': '连接',
    'action.disconnect': '断开',
    'action.copy_link': '复制链接',
    'status.queued': '排队中',
    'status.running': '运行中',
    'status.completed': '已完成',
    'status.failed': '失败',
    'status.download_failed': '下载失败',
    'status.active': '已激活',
    'status.disabled': '已禁用',
    'status.connected': '已连接',
    'status.disconnected': '未连接',
    'label.model': '逻辑模型',
    'label.concurrency': '并发数',
    'label.count': '生成数量',
    'label.range': '分镜范围',
    'label.range_hint': '例如: 1-5, 8, 10 (留空为全部)',
    'label.provider': '供应商',
    'label.priority': '优先级',
    'label.weight': '权重',
    'label.language': '界面语言',
    'label.prompt': '提示词',
    'label.intent': '导演意图',
    'label.duration': '时长 (秒)',
    'label.resolution': '分辨率',
    'label.is_pro': '启用 Pro 模式 (高质量)',
    'label.assets': '资产信息',
    'label.scene': '场景',
    'label.props': '道具',
    'label.chars': '角色',
    'label.chars_hint': '格式: 姓名 或 姓名 @ID',
    'label.output_mode': '输出模式',
    'label.custom_path': '自定义路径',
    'label.dry_run': '空跑测试 (Dry Run)',
    'label.force': '强制执行 (忽略缓存)',
    'label.exec_options': '执行选项',
    'label.search_hint': '搜索提示词或编号...',
    'label.system_version': '系统版本',
    'label.tag_placeholder': '输入并回车添加...',
    'label.run_progress': '任务进度概览',
    'label.error_code': '错误码',
    'label.error_msg': '错误信息',
    'opt.mode_centralized': '集中式 (Results 目录)',
    'opt.mode_inplace': '原位 (分镜目录)',
    'opt.mode_custom': '自定义路径',
    'msg.upload_success': '脚本导入成功',
    'msg.create_run_success': '任务创建成功',
    'msg.save_success': '保存成功',
    'msg.confirm_delete': '确认删除此记录？此操作不可恢复。',
    'msg.task_queued': '任务已加入重试队列',
    'error.upload_failed': '导入失败，请检查文件格式',
    'error.delete_failed': '删除失败',
    'error.generic': '发生错误，请重试',
    'error.schema_validation': '参数校验失败，请检查输入',
    'dash.recent_runs': '最近运行',
    'dash.stats_overview': '数据概览',
    'dash.active_tasks': '活跃任务',
    'dash.total_runs': '总运行次数',
    'dash.success_rate': '成功率',
    'dash.welcome': '欢迎回到 CineFlow 控制台',
    'title.results': '结果库',
    'title.settings': '系统设置',
    'tab.general': '常规',
    'tab.models': '模型管理',
    'tab.providers': '供应商管理',
    'col.model_name': '模型名称',
    'col.description': '描述',
    'col.status': '状态',
    'col.actions': '操作',
    'col.type': '类型',
    'col.capabilities': '能力',
    'col.id': '编号',
    'col.name': '名称',
    'col.segments': '分镜数',
    'col.created': '创建时间',
    'col.progress': '进度',
    'col.tasks': '任务数',
    'res.no_media': '暂无媒体',
    'res.no_ref': '无参考图',
    'res.na': '无',
    'res.task_prefix': '任务: ',
    'res.seg_prefix': '分镜 #',
    'res.loading': '正在加载结果库...',
    'res.empty': '暂无结果。请先创建并运行任务。',
    'res.generated_count': '个已生成视频',
    'filter.media_type': '媒体类型',
    'filter.all_media': '全部媒体',
    'filter.video_only': '仅视频',
    'filter.date_range': '时间范围',
    'filter.all_time': '全部时间',
    'filter.today': '今天',
    'filter.week': '最近7天',
    'filter.status': '状态',
    'filter.all_status': '全部状态',
    'filter.failed_retryable': '失败 (可重试)',
    'state.loading': '加载中...',
    'state.empty': '暂无数据',
    'file.storyboard_json': 'storyboard.json 文件',
  },
  'en-US': {
    'app.title': 'CineFlow Console',
    'nav.dashboard': 'Dashboard',
    'nav.storyboards': 'Storyboards',
    'nav.runs': 'Runs',
    'nav.results': 'Results',
    'nav.settings': 'Settings',
    'action.import': 'Import',
    'action.create_run': 'Create Run',
    'action.save': 'Save',
    'action.cancel': 'Cancel',
    'action.delete': 'Delete',
    'action.retry': 'Retry',
    'action.view': 'View',
    'action.edit': 'Edit',
    'action.filter': 'Filter',
    'action.download': 'Download Video',
    'action.download_meta': 'Download Metadata',
    'action.enable': 'Enable',
    'action.disable': 'Disable',
    'action.details': 'Details',
    'action.upload_ref': 'Upload Ref',
    'action.upload_click': 'Click to Upload',
    'action.apply_filter': 'Apply Filter',
    'action.clear_filter': 'Clear Filter',
    'action.connect': 'Connect',
    'action.disconnect': 'Disconnect',
    'action.copy_link': 'Copy Link',
    'status.queued': 'Queued',
    'status.running': 'Running',
    'status.completed': 'Completed',
    'status.failed': 'Failed',
    'status.download_failed': 'Download Failed',
    'status.active': 'Active',
    'status.disabled': 'Disabled',
    'status.connected': 'Connected',
    'status.disconnected': 'Disconnected',
    'label.model': 'Logical Model',
    'label.concurrency': 'Concurrency',
    'label.count': 'Gen Count',
    'label.range': 'Segments Range',
    'label.range_hint': 'e.g. 1-5, 8, 10 (Empty for all)',
    'label.provider': 'Provider',
    'label.priority': 'Priority',
    'label.weight': 'Weight',
    'label.language': 'Language',
    'label.prompt': 'Prompt',
    'label.intent': 'Director Intent',
    'label.duration': 'Duration (sec)',
    'label.resolution': 'Resolution',
    'label.is_pro': 'Enable Pro Mode',
    'label.assets': 'Assets',
    'label.scene': 'Scene',
    'label.props': 'Props',
    'label.chars': 'Characters',
    'label.chars_hint': 'Format: Name or Name @ID',
    'label.output_mode': 'Output Mode',
    'label.custom_path': 'Custom Path',
    'label.dry_run': 'Dry Run',
    'label.force': 'Force (Ignore Cache)',
    'label.exec_options': 'Execution Options',
    'label.search_hint': 'Search prompt or index...',
    'label.system_version': 'System Version',
    'label.tag_placeholder': 'Type and press Enter...',
    'label.run_progress': 'Run Progress',
    'label.error_code': 'Error Code',
    'label.error_msg': 'Error Message',
    'opt.mode_centralized': 'Centralized',
    'opt.mode_inplace': 'In Place',
    'opt.mode_custom': 'Custom',
    'msg.upload_success': 'Import Successful',
    'msg.create_run_success': 'Run Created Successfully',
    'msg.save_success': 'Saved Successfully',
    'msg.confirm_delete': 'Are you sure you want to delete? This cannot be undone.',
    'msg.task_queued': 'Task queued for retry',
    'error.upload_failed': 'Import Failed, check file format',
    'error.delete_failed': 'Delete Failed',
    'error.generic': 'An error occurred',
    'error.schema_validation': 'Validation Error',
    'dash.recent_runs': 'Recent Runs',
    'dash.stats_overview': 'Overview',
    'dash.active_tasks': 'Active Tasks',
    'dash.total_runs': 'Total Runs',
    'dash.success_rate': 'Success Rate',
    'dash.welcome': 'Welcome back to CineFlow Console',
    'title.results': 'Results Library',
    'title.settings': 'Settings',
    'tab.general': 'General',
    'tab.models': 'Models',
    'tab.providers': 'Providers',
    'col.model_name': 'Model Name',
    'col.description': 'Description',
    'col.status': 'Status',
    'col.actions': 'Actions',
    'col.type': 'Type',
    'col.capabilities': 'Capabilities',
    'col.id': 'ID',
    'col.name': 'Name',
    'col.segments': 'Segments',
    'col.created': 'Created',
    'col.progress': 'Progress',
    'col.tasks': 'Tasks',
    'res.no_media': 'No Media',
    'res.no_ref': 'No Ref',
    'res.na': 'N/A',
    'res.task_prefix': 'Task: ',
    'res.seg_prefix': 'Seg #',
    'res.loading': 'Loading library...',
    'res.empty': 'No results found. Start a run to generate videos.',
    'res.generated_count': 'generated videos available',
    'filter.media_type': 'Media Type',
    'filter.all_media': 'All Media',
    'filter.video_only': 'Video Only',
    'filter.date_range': 'Date Range',
    'filter.all_time': 'All Time',
    'filter.today': 'Today',
    'filter.week': 'Last 7 Days',
    'filter.status': 'Status',
    'filter.all_status': 'All Status',
    'filter.failed_retryable': 'Failed (Retryable)',
    'state.loading': 'Loading...',
    'state.empty': 'No Data',
    'file.storyboard_json': 'storyboard.json file',
  },
};
